package com.btjf.credit.report.model;

import java.io.Serializable;
import java.util.Date;

public class CreditReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FApplyUserId
     *
     * @mbg.generated
     */
    private Integer applyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FApplyUserType
     *
     * @mbg.generated
     */
    private Integer applyUserType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FApplyTime
     *
     * @mbg.generated
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FCustomerName
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FCustomerIdCardNum
     *
     * @mbg.generated
     */
    private String customerIdCardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FCustomerMobile
     *
     * @mbg.generated
     */
    private String customerMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FEmpId
     *
     * @mbg.generated
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FReportNum
     *
     * @mbg.generated
     */
    private String reportNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FReportType
     *
     * @mbg.generated
     */
    private Integer reportType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FStatus
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FResultNotifyTime
     *
     * @mbg.generated
     */
    private Date resultNotifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FReportCode
     *
     * @mbg.generated
     */
    private String reportCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FIsReaded
     *
     * @mbg.generated
     */
    private Boolean isReaded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FReadTime
     *
     * @mbg.generated
     */
    private Date readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FIsFeedBacked
     *
     * @mbg.generated
     */
    private Boolean isFeedBacked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FIsUseful
     *
     * @mbg.generated
     */
    private Boolean isUseful;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FFeedBackTime
     *
     * @mbg.generated
     */
    private Date feedBackTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FCreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FCreateUserId
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FLastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FLastModifyUserId
     *
     * @mbg.generated
     */
    private Integer lastModifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FIsDelete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FReportDesc
     *
     * @mbg.generated
     */
    private String reportDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FCustomerBankCard
     *
     * @mbg.generated
     */
    private String customerBankCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FUuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReport.FReportContent
     *
     * @mbg.generated
     */
    private String reportContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FID
     *
     * @return the value of t_CreditReport.FID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FID
     *
     * @param id the value for t_CreditReport.FID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FApplyUserId
     *
     * @return the value of t_CreditReport.FApplyUserId
     *
     * @mbg.generated
     */
    public Integer getApplyUserId() {
        return applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FApplyUserId
     *
     * @param applyUserId the value for t_CreditReport.FApplyUserId
     *
     * @mbg.generated
     */
    public void setApplyUserId(Integer applyUserId) {
        this.applyUserId = applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FApplyUserType
     *
     * @return the value of t_CreditReport.FApplyUserType
     *
     * @mbg.generated
     */
    public Integer getApplyUserType() {
        return applyUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FApplyUserType
     *
     * @param applyUserType the value for t_CreditReport.FApplyUserType
     *
     * @mbg.generated
     */
    public void setApplyUserType(Integer applyUserType) {
        this.applyUserType = applyUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FApplyTime
     *
     * @return the value of t_CreditReport.FApplyTime
     *
     * @mbg.generated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FApplyTime
     *
     * @param applyTime the value for t_CreditReport.FApplyTime
     *
     * @mbg.generated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FCustomerName
     *
     * @return the value of t_CreditReport.FCustomerName
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FCustomerName
     *
     * @param customerName the value for t_CreditReport.FCustomerName
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FCustomerIdCardNum
     *
     * @return the value of t_CreditReport.FCustomerIdCardNum
     *
     * @mbg.generated
     */
    public String getCustomerIdCardNum() {
        return customerIdCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FCustomerIdCardNum
     *
     * @param customerIdCardNum the value for t_CreditReport.FCustomerIdCardNum
     *
     * @mbg.generated
     */
    public void setCustomerIdCardNum(String customerIdCardNum) {
        this.customerIdCardNum = customerIdCardNum == null ? null : customerIdCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FCustomerMobile
     *
     * @return the value of t_CreditReport.FCustomerMobile
     *
     * @mbg.generated
     */
    public String getCustomerMobile() {
        return customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FCustomerMobile
     *
     * @param customerMobile the value for t_CreditReport.FCustomerMobile
     *
     * @mbg.generated
     */
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile == null ? null : customerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FEmpId
     *
     * @return the value of t_CreditReport.FEmpId
     *
     * @mbg.generated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FEmpId
     *
     * @param empId the value for t_CreditReport.FEmpId
     *
     * @mbg.generated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FReportNum
     *
     * @return the value of t_CreditReport.FReportNum
     *
     * @mbg.generated
     */
    public String getReportNum() {
        return reportNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FReportNum
     *
     * @param reportNum the value for t_CreditReport.FReportNum
     *
     * @mbg.generated
     */
    public void setReportNum(String reportNum) {
        this.reportNum = reportNum == null ? null : reportNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FReportType
     *
     * @return the value of t_CreditReport.FReportType
     *
     * @mbg.generated
     */
    public Integer getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FReportType
     *
     * @param reportType the value for t_CreditReport.FReportType
     *
     * @mbg.generated
     */
    public void setReportType(Integer reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FStatus
     *
     * @return the value of t_CreditReport.FStatus
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FStatus
     *
     * @param status the value for t_CreditReport.FStatus
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FResultNotifyTime
     *
     * @return the value of t_CreditReport.FResultNotifyTime
     *
     * @mbg.generated
     */
    public Date getResultNotifyTime() {
        return resultNotifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FResultNotifyTime
     *
     * @param resultNotifyTime the value for t_CreditReport.FResultNotifyTime
     *
     * @mbg.generated
     */
    public void setResultNotifyTime(Date resultNotifyTime) {
        this.resultNotifyTime = resultNotifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FReportCode
     *
     * @return the value of t_CreditReport.FReportCode
     *
     * @mbg.generated
     */
    public String getReportCode() {
        return reportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FReportCode
     *
     * @param reportCode the value for t_CreditReport.FReportCode
     *
     * @mbg.generated
     */
    public void setReportCode(String reportCode) {
        this.reportCode = reportCode == null ? null : reportCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FIsReaded
     *
     * @return the value of t_CreditReport.FIsReaded
     *
     * @mbg.generated
     */
    public Boolean getIsReaded() {
        return isReaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FIsReaded
     *
     * @param isReaded the value for t_CreditReport.FIsReaded
     *
     * @mbg.generated
     */
    public void setIsReaded(Boolean isReaded) {
        this.isReaded = isReaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FReadTime
     *
     * @return the value of t_CreditReport.FReadTime
     *
     * @mbg.generated
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FReadTime
     *
     * @param readTime the value for t_CreditReport.FReadTime
     *
     * @mbg.generated
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FIsFeedBacked
     *
     * @return the value of t_CreditReport.FIsFeedBacked
     *
     * @mbg.generated
     */
    public Boolean getIsFeedBacked() {
        return isFeedBacked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FIsFeedBacked
     *
     * @param isFeedBacked the value for t_CreditReport.FIsFeedBacked
     *
     * @mbg.generated
     */
    public void setIsFeedBacked(Boolean isFeedBacked) {
        this.isFeedBacked = isFeedBacked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FIsUseful
     *
     * @return the value of t_CreditReport.FIsUseful
     *
     * @mbg.generated
     */
    public Boolean getIsUseful() {
        return isUseful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FIsUseful
     *
     * @param isUseful the value for t_CreditReport.FIsUseful
     *
     * @mbg.generated
     */
    public void setIsUseful(Boolean isUseful) {
        this.isUseful = isUseful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FFeedBackTime
     *
     * @return the value of t_CreditReport.FFeedBackTime
     *
     * @mbg.generated
     */
    public Date getFeedBackTime() {
        return feedBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FFeedBackTime
     *
     * @param feedBackTime the value for t_CreditReport.FFeedBackTime
     *
     * @mbg.generated
     */
    public void setFeedBackTime(Date feedBackTime) {
        this.feedBackTime = feedBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FCreateTime
     *
     * @return the value of t_CreditReport.FCreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FCreateTime
     *
     * @param createTime the value for t_CreditReport.FCreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FCreateUserId
     *
     * @return the value of t_CreditReport.FCreateUserId
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FCreateUserId
     *
     * @param createUserId the value for t_CreditReport.FCreateUserId
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FLastModifyTime
     *
     * @return the value of t_CreditReport.FLastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FLastModifyTime
     *
     * @param lastModifyTime the value for t_CreditReport.FLastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FLastModifyUserId
     *
     * @return the value of t_CreditReport.FLastModifyUserId
     *
     * @mbg.generated
     */
    public Integer getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FLastModifyUserId
     *
     * @param lastModifyUserId the value for t_CreditReport.FLastModifyUserId
     *
     * @mbg.generated
     */
    public void setLastModifyUserId(Integer lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FIsDelete
     *
     * @return the value of t_CreditReport.FIsDelete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FIsDelete
     *
     * @param isDelete the value for t_CreditReport.FIsDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FReportDesc
     *
     * @return the value of t_CreditReport.FReportDesc
     *
     * @mbg.generated
     */
    public String getReportDesc() {
        return reportDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FReportDesc
     *
     * @param reportDesc the value for t_CreditReport.FReportDesc
     *
     * @mbg.generated
     */
    public void setReportDesc(String reportDesc) {
        this.reportDesc = reportDesc == null ? null : reportDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FCustomerBankCard
     *
     * @return the value of t_CreditReport.FCustomerBankCard
     *
     * @mbg.generated
     */
    public String getCustomerBankCard() {
        return customerBankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FCustomerBankCard
     *
     * @param customerBankCard the value for t_CreditReport.FCustomerBankCard
     *
     * @mbg.generated
     */
    public void setCustomerBankCard(String customerBankCard) {
        this.customerBankCard = customerBankCard == null ? null : customerBankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FUuid
     *
     * @return the value of t_CreditReport.FUuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FUuid
     *
     * @param uuid the value for t_CreditReport.FUuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReport.FReportContent
     *
     * @return the value of t_CreditReport.FReportContent
     *
     * @mbg.generated
     */
    public String getReportContent() {
        return reportContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReport.FReportContent
     *
     * @param reportContent the value for t_CreditReport.FReportContent
     *
     * @mbg.generated
     */
    public void setReportContent(String reportContent) {
        this.reportContent = reportContent == null ? null : reportContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CreditReport other = (CreditReport) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getApplyUserId() == null ? other.getApplyUserId() == null : this.getApplyUserId().equals(other.getApplyUserId()))
            && (this.getApplyUserType() == null ? other.getApplyUserType() == null : this.getApplyUserType().equals(other.getApplyUserType()))
            && (this.getApplyTime() == null ? other.getApplyTime() == null : this.getApplyTime().equals(other.getApplyTime()))
            && (this.getCustomerName() == null ? other.getCustomerName() == null : this.getCustomerName().equals(other.getCustomerName()))
            && (this.getCustomerIdCardNum() == null ? other.getCustomerIdCardNum() == null : this.getCustomerIdCardNum().equals(other.getCustomerIdCardNum()))
            && (this.getCustomerMobile() == null ? other.getCustomerMobile() == null : this.getCustomerMobile().equals(other.getCustomerMobile()))
            && (this.getEmpId() == null ? other.getEmpId() == null : this.getEmpId().equals(other.getEmpId()))
            && (this.getReportNum() == null ? other.getReportNum() == null : this.getReportNum().equals(other.getReportNum()))
            && (this.getReportType() == null ? other.getReportType() == null : this.getReportType().equals(other.getReportType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getResultNotifyTime() == null ? other.getResultNotifyTime() == null : this.getResultNotifyTime().equals(other.getResultNotifyTime()))
            && (this.getReportCode() == null ? other.getReportCode() == null : this.getReportCode().equals(other.getReportCode()))
            && (this.getIsReaded() == null ? other.getIsReaded() == null : this.getIsReaded().equals(other.getIsReaded()))
            && (this.getReadTime() == null ? other.getReadTime() == null : this.getReadTime().equals(other.getReadTime()))
            && (this.getIsFeedBacked() == null ? other.getIsFeedBacked() == null : this.getIsFeedBacked().equals(other.getIsFeedBacked()))
            && (this.getIsUseful() == null ? other.getIsUseful() == null : this.getIsUseful().equals(other.getIsUseful()))
            && (this.getFeedBackTime() == null ? other.getFeedBackTime() == null : this.getFeedBackTime().equals(other.getFeedBackTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getLastModifyUserId() == null ? other.getLastModifyUserId() == null : this.getLastModifyUserId().equals(other.getLastModifyUserId()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getReportDesc() == null ? other.getReportDesc() == null : this.getReportDesc().equals(other.getReportDesc()))
            && (this.getCustomerBankCard() == null ? other.getCustomerBankCard() == null : this.getCustomerBankCard().equals(other.getCustomerBankCard()))
            && (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getReportContent() == null ? other.getReportContent() == null : this.getReportContent().equals(other.getReportContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getApplyUserId() == null) ? 0 : getApplyUserId().hashCode());
        result = prime * result + ((getApplyUserType() == null) ? 0 : getApplyUserType().hashCode());
        result = prime * result + ((getApplyTime() == null) ? 0 : getApplyTime().hashCode());
        result = prime * result + ((getCustomerName() == null) ? 0 : getCustomerName().hashCode());
        result = prime * result + ((getCustomerIdCardNum() == null) ? 0 : getCustomerIdCardNum().hashCode());
        result = prime * result + ((getCustomerMobile() == null) ? 0 : getCustomerMobile().hashCode());
        result = prime * result + ((getEmpId() == null) ? 0 : getEmpId().hashCode());
        result = prime * result + ((getReportNum() == null) ? 0 : getReportNum().hashCode());
        result = prime * result + ((getReportType() == null) ? 0 : getReportType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getResultNotifyTime() == null) ? 0 : getResultNotifyTime().hashCode());
        result = prime * result + ((getReportCode() == null) ? 0 : getReportCode().hashCode());
        result = prime * result + ((getIsReaded() == null) ? 0 : getIsReaded().hashCode());
        result = prime * result + ((getReadTime() == null) ? 0 : getReadTime().hashCode());
        result = prime * result + ((getIsFeedBacked() == null) ? 0 : getIsFeedBacked().hashCode());
        result = prime * result + ((getIsUseful() == null) ? 0 : getIsUseful().hashCode());
        result = prime * result + ((getFeedBackTime() == null) ? 0 : getFeedBackTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getLastModifyUserId() == null) ? 0 : getLastModifyUserId().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getReportDesc() == null) ? 0 : getReportDesc().hashCode());
        result = prime * result + ((getCustomerBankCard() == null) ? 0 : getCustomerBankCard().hashCode());
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getReportContent() == null) ? 0 : getReportContent().hashCode());
        return result;
    }
}