package com.btjf.credit.report.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CreditReportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public CreditReportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("FID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("FID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("FID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("FID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("FID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("FID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("FID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("FID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("FID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("FID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNull() {
            addCriterion("FApplyUserId is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNotNull() {
            addCriterion("FApplyUserId is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdEqualTo(Integer value) {
            addCriterion("FApplyUserId =", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotEqualTo(Integer value) {
            addCriterion("FApplyUserId <>", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThan(Integer value) {
            addCriterion("FApplyUserId >", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FApplyUserId >=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThan(Integer value) {
            addCriterion("FApplyUserId <", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("FApplyUserId <=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIn(List<Integer> values) {
            addCriterion("FApplyUserId in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotIn(List<Integer> values) {
            addCriterion("FApplyUserId not in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("FApplyUserId between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FApplyUserId not between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeIsNull() {
            addCriterion("FApplyUserType is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeIsNotNull() {
            addCriterion("FApplyUserType is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeEqualTo(Integer value) {
            addCriterion("FApplyUserType =", value, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeNotEqualTo(Integer value) {
            addCriterion("FApplyUserType <>", value, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeGreaterThan(Integer value) {
            addCriterion("FApplyUserType >", value, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("FApplyUserType >=", value, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeLessThan(Integer value) {
            addCriterion("FApplyUserType <", value, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeLessThanOrEqualTo(Integer value) {
            addCriterion("FApplyUserType <=", value, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeIn(List<Integer> values) {
            addCriterion("FApplyUserType in", values, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeNotIn(List<Integer> values) {
            addCriterion("FApplyUserType not in", values, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeBetween(Integer value1, Integer value2) {
            addCriterion("FApplyUserType between", value1, value2, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyUserTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("FApplyUserType not between", value1, value2, "applyUserType");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNull() {
            addCriterion("FApplyTime is null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNotNull() {
            addCriterion("FApplyTime is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeEqualTo(Date value) {
            addCriterion("FApplyTime =", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotEqualTo(Date value) {
            addCriterion("FApplyTime <>", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThan(Date value) {
            addCriterion("FApplyTime >", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FApplyTime >=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThan(Date value) {
            addCriterion("FApplyTime <", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThanOrEqualTo(Date value) {
            addCriterion("FApplyTime <=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIn(List<Date> values) {
            addCriterion("FApplyTime in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotIn(List<Date> values) {
            addCriterion("FApplyTime not in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeBetween(Date value1, Date value2) {
            addCriterion("FApplyTime between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotBetween(Date value1, Date value2) {
            addCriterion("FApplyTime not between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("FCustomerName is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("FCustomerName is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("FCustomerName =", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("FCustomerName <>", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("FCustomerName >", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("FCustomerName >=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("FCustomerName <", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("FCustomerName <=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("FCustomerName like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("FCustomerName not like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIn(List<String> values) {
            addCriterion("FCustomerName in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotIn(List<String> values) {
            addCriterion("FCustomerName not in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("FCustomerName between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("FCustomerName not between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumIsNull() {
            addCriterion("FCustomerIdCardNum is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumIsNotNull() {
            addCriterion("FCustomerIdCardNum is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumEqualTo(String value) {
            addCriterion("FCustomerIdCardNum =", value, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumNotEqualTo(String value) {
            addCriterion("FCustomerIdCardNum <>", value, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumGreaterThan(String value) {
            addCriterion("FCustomerIdCardNum >", value, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumGreaterThanOrEqualTo(String value) {
            addCriterion("FCustomerIdCardNum >=", value, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumLessThan(String value) {
            addCriterion("FCustomerIdCardNum <", value, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumLessThanOrEqualTo(String value) {
            addCriterion("FCustomerIdCardNum <=", value, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumLike(String value) {
            addCriterion("FCustomerIdCardNum like", value, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumNotLike(String value) {
            addCriterion("FCustomerIdCardNum not like", value, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumIn(List<String> values) {
            addCriterion("FCustomerIdCardNum in", values, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumNotIn(List<String> values) {
            addCriterion("FCustomerIdCardNum not in", values, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumBetween(String value1, String value2) {
            addCriterion("FCustomerIdCardNum between", value1, value2, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumNotBetween(String value1, String value2) {
            addCriterion("FCustomerIdCardNum not between", value1, value2, "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileIsNull() {
            addCriterion("FCustomerMobile is null");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileIsNotNull() {
            addCriterion("FCustomerMobile is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileEqualTo(String value) {
            addCriterion("FCustomerMobile =", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotEqualTo(String value) {
            addCriterion("FCustomerMobile <>", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileGreaterThan(String value) {
            addCriterion("FCustomerMobile >", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileGreaterThanOrEqualTo(String value) {
            addCriterion("FCustomerMobile >=", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLessThan(String value) {
            addCriterion("FCustomerMobile <", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLessThanOrEqualTo(String value) {
            addCriterion("FCustomerMobile <=", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLike(String value) {
            addCriterion("FCustomerMobile like", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotLike(String value) {
            addCriterion("FCustomerMobile not like", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileIn(List<String> values) {
            addCriterion("FCustomerMobile in", values, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotIn(List<String> values) {
            addCriterion("FCustomerMobile not in", values, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileBetween(String value1, String value2) {
            addCriterion("FCustomerMobile between", value1, value2, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotBetween(String value1, String value2) {
            addCriterion("FCustomerMobile not between", value1, value2, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNull() {
            addCriterion("FEmpId is null");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNotNull() {
            addCriterion("FEmpId is not null");
            return (Criteria) this;
        }

        public Criteria andEmpIdEqualTo(Integer value) {
            addCriterion("FEmpId =", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotEqualTo(Integer value) {
            addCriterion("FEmpId <>", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThan(Integer value) {
            addCriterion("FEmpId >", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FEmpId >=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThan(Integer value) {
            addCriterion("FEmpId <", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThanOrEqualTo(Integer value) {
            addCriterion("FEmpId <=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdIn(List<Integer> values) {
            addCriterion("FEmpId in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotIn(List<Integer> values) {
            addCriterion("FEmpId not in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdBetween(Integer value1, Integer value2) {
            addCriterion("FEmpId between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FEmpId not between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andReportNumIsNull() {
            addCriterion("FReportNum is null");
            return (Criteria) this;
        }

        public Criteria andReportNumIsNotNull() {
            addCriterion("FReportNum is not null");
            return (Criteria) this;
        }

        public Criteria andReportNumEqualTo(String value) {
            addCriterion("FReportNum =", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotEqualTo(String value) {
            addCriterion("FReportNum <>", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumGreaterThan(String value) {
            addCriterion("FReportNum >", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumGreaterThanOrEqualTo(String value) {
            addCriterion("FReportNum >=", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumLessThan(String value) {
            addCriterion("FReportNum <", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumLessThanOrEqualTo(String value) {
            addCriterion("FReportNum <=", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumLike(String value) {
            addCriterion("FReportNum like", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotLike(String value) {
            addCriterion("FReportNum not like", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumIn(List<String> values) {
            addCriterion("FReportNum in", values, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotIn(List<String> values) {
            addCriterion("FReportNum not in", values, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumBetween(String value1, String value2) {
            addCriterion("FReportNum between", value1, value2, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotBetween(String value1, String value2) {
            addCriterion("FReportNum not between", value1, value2, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportTypeIsNull() {
            addCriterion("FReportType is null");
            return (Criteria) this;
        }

        public Criteria andReportTypeIsNotNull() {
            addCriterion("FReportType is not null");
            return (Criteria) this;
        }

        public Criteria andReportTypeEqualTo(Integer value) {
            addCriterion("FReportType =", value, "reportType");
            return (Criteria) this;
        }

        public Criteria andReportTypeNotEqualTo(Integer value) {
            addCriterion("FReportType <>", value, "reportType");
            return (Criteria) this;
        }

        public Criteria andReportTypeGreaterThan(Integer value) {
            addCriterion("FReportType >", value, "reportType");
            return (Criteria) this;
        }

        public Criteria andReportTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("FReportType >=", value, "reportType");
            return (Criteria) this;
        }

        public Criteria andReportTypeLessThan(Integer value) {
            addCriterion("FReportType <", value, "reportType");
            return (Criteria) this;
        }

        public Criteria andReportTypeLessThanOrEqualTo(Integer value) {
            addCriterion("FReportType <=", value, "reportType");
            return (Criteria) this;
        }

        public Criteria andReportTypeIn(List<Integer> values) {
            addCriterion("FReportType in", values, "reportType");
            return (Criteria) this;
        }

        public Criteria andReportTypeNotIn(List<Integer> values) {
            addCriterion("FReportType not in", values, "reportType");
            return (Criteria) this;
        }

        public Criteria andReportTypeBetween(Integer value1, Integer value2) {
            addCriterion("FReportType between", value1, value2, "reportType");
            return (Criteria) this;
        }

        public Criteria andReportTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("FReportType not between", value1, value2, "reportType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("FStatus is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("FStatus is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("FStatus =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("FStatus <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("FStatus >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("FStatus >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("FStatus <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("FStatus <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("FStatus in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("FStatus not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("FStatus between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("FStatus not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeIsNull() {
            addCriterion("FResultNotifyTime is null");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeIsNotNull() {
            addCriterion("FResultNotifyTime is not null");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeEqualTo(Date value) {
            addCriterion("FResultNotifyTime =", value, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeNotEqualTo(Date value) {
            addCriterion("FResultNotifyTime <>", value, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeGreaterThan(Date value) {
            addCriterion("FResultNotifyTime >", value, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FResultNotifyTime >=", value, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeLessThan(Date value) {
            addCriterion("FResultNotifyTime <", value, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("FResultNotifyTime <=", value, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeIn(List<Date> values) {
            addCriterion("FResultNotifyTime in", values, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeNotIn(List<Date> values) {
            addCriterion("FResultNotifyTime not in", values, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeBetween(Date value1, Date value2) {
            addCriterion("FResultNotifyTime between", value1, value2, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andResultNotifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("FResultNotifyTime not between", value1, value2, "resultNotifyTime");
            return (Criteria) this;
        }

        public Criteria andReportCodeIsNull() {
            addCriterion("FReportCode is null");
            return (Criteria) this;
        }

        public Criteria andReportCodeIsNotNull() {
            addCriterion("FReportCode is not null");
            return (Criteria) this;
        }

        public Criteria andReportCodeEqualTo(String value) {
            addCriterion("FReportCode =", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotEqualTo(String value) {
            addCriterion("FReportCode <>", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeGreaterThan(String value) {
            addCriterion("FReportCode >", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FReportCode >=", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLessThan(String value) {
            addCriterion("FReportCode <", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLessThanOrEqualTo(String value) {
            addCriterion("FReportCode <=", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLike(String value) {
            addCriterion("FReportCode like", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotLike(String value) {
            addCriterion("FReportCode not like", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeIn(List<String> values) {
            addCriterion("FReportCode in", values, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotIn(List<String> values) {
            addCriterion("FReportCode not in", values, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeBetween(String value1, String value2) {
            addCriterion("FReportCode between", value1, value2, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotBetween(String value1, String value2) {
            addCriterion("FReportCode not between", value1, value2, "reportCode");
            return (Criteria) this;
        }

        public Criteria andIsReadedIsNull() {
            addCriterion("FIsReaded is null");
            return (Criteria) this;
        }

        public Criteria andIsReadedIsNotNull() {
            addCriterion("FIsReaded is not null");
            return (Criteria) this;
        }

        public Criteria andIsReadedEqualTo(Boolean value) {
            addCriterion("FIsReaded =", value, "isReaded");
            return (Criteria) this;
        }

        public Criteria andIsReadedNotEqualTo(Boolean value) {
            addCriterion("FIsReaded <>", value, "isReaded");
            return (Criteria) this;
        }

        public Criteria andIsReadedGreaterThan(Boolean value) {
            addCriterion("FIsReaded >", value, "isReaded");
            return (Criteria) this;
        }

        public Criteria andIsReadedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FIsReaded >=", value, "isReaded");
            return (Criteria) this;
        }

        public Criteria andIsReadedLessThan(Boolean value) {
            addCriterion("FIsReaded <", value, "isReaded");
            return (Criteria) this;
        }

        public Criteria andIsReadedLessThanOrEqualTo(Boolean value) {
            addCriterion("FIsReaded <=", value, "isReaded");
            return (Criteria) this;
        }

        public Criteria andIsReadedIn(List<Boolean> values) {
            addCriterion("FIsReaded in", values, "isReaded");
            return (Criteria) this;
        }

        public Criteria andIsReadedNotIn(List<Boolean> values) {
            addCriterion("FIsReaded not in", values, "isReaded");
            return (Criteria) this;
        }

        public Criteria andIsReadedBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsReaded between", value1, value2, "isReaded");
            return (Criteria) this;
        }

        public Criteria andIsReadedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsReaded not between", value1, value2, "isReaded");
            return (Criteria) this;
        }

        public Criteria andReadTimeIsNull() {
            addCriterion("FReadTime is null");
            return (Criteria) this;
        }

        public Criteria andReadTimeIsNotNull() {
            addCriterion("FReadTime is not null");
            return (Criteria) this;
        }

        public Criteria andReadTimeEqualTo(Date value) {
            addCriterion("FReadTime =", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeNotEqualTo(Date value) {
            addCriterion("FReadTime <>", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeGreaterThan(Date value) {
            addCriterion("FReadTime >", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FReadTime >=", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeLessThan(Date value) {
            addCriterion("FReadTime <", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeLessThanOrEqualTo(Date value) {
            addCriterion("FReadTime <=", value, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeIn(List<Date> values) {
            addCriterion("FReadTime in", values, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeNotIn(List<Date> values) {
            addCriterion("FReadTime not in", values, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeBetween(Date value1, Date value2) {
            addCriterion("FReadTime between", value1, value2, "readTime");
            return (Criteria) this;
        }

        public Criteria andReadTimeNotBetween(Date value1, Date value2) {
            addCriterion("FReadTime not between", value1, value2, "readTime");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedIsNull() {
            addCriterion("FIsFeedBacked is null");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedIsNotNull() {
            addCriterion("FIsFeedBacked is not null");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedEqualTo(Boolean value) {
            addCriterion("FIsFeedBacked =", value, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedNotEqualTo(Boolean value) {
            addCriterion("FIsFeedBacked <>", value, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedGreaterThan(Boolean value) {
            addCriterion("FIsFeedBacked >", value, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FIsFeedBacked >=", value, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedLessThan(Boolean value) {
            addCriterion("FIsFeedBacked <", value, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedLessThanOrEqualTo(Boolean value) {
            addCriterion("FIsFeedBacked <=", value, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedIn(List<Boolean> values) {
            addCriterion("FIsFeedBacked in", values, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedNotIn(List<Boolean> values) {
            addCriterion("FIsFeedBacked not in", values, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsFeedBacked between", value1, value2, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsFeedBackedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsFeedBacked not between", value1, value2, "isFeedBacked");
            return (Criteria) this;
        }

        public Criteria andIsUsefulIsNull() {
            addCriterion("FIsUseful is null");
            return (Criteria) this;
        }

        public Criteria andIsUsefulIsNotNull() {
            addCriterion("FIsUseful is not null");
            return (Criteria) this;
        }

        public Criteria andIsUsefulEqualTo(Boolean value) {
            addCriterion("FIsUseful =", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulNotEqualTo(Boolean value) {
            addCriterion("FIsUseful <>", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulGreaterThan(Boolean value) {
            addCriterion("FIsUseful >", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FIsUseful >=", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulLessThan(Boolean value) {
            addCriterion("FIsUseful <", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulLessThanOrEqualTo(Boolean value) {
            addCriterion("FIsUseful <=", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulIn(List<Boolean> values) {
            addCriterion("FIsUseful in", values, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulNotIn(List<Boolean> values) {
            addCriterion("FIsUseful not in", values, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsUseful between", value1, value2, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsUseful not between", value1, value2, "isUseful");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeIsNull() {
            addCriterion("FFeedBackTime is null");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeIsNotNull() {
            addCriterion("FFeedBackTime is not null");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeEqualTo(Date value) {
            addCriterion("FFeedBackTime =", value, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeNotEqualTo(Date value) {
            addCriterion("FFeedBackTime <>", value, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeGreaterThan(Date value) {
            addCriterion("FFeedBackTime >", value, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FFeedBackTime >=", value, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeLessThan(Date value) {
            addCriterion("FFeedBackTime <", value, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeLessThanOrEqualTo(Date value) {
            addCriterion("FFeedBackTime <=", value, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeIn(List<Date> values) {
            addCriterion("FFeedBackTime in", values, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeNotIn(List<Date> values) {
            addCriterion("FFeedBackTime not in", values, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeBetween(Date value1, Date value2) {
            addCriterion("FFeedBackTime between", value1, value2, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andFeedBackTimeNotBetween(Date value1, Date value2) {
            addCriterion("FFeedBackTime not between", value1, value2, "feedBackTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("FCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("FCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("FCreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("FCreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("FCreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FCreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("FCreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("FCreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("FCreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("FCreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("FCreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("FCreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("FCreateUserId is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("FCreateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("FCreateUserId =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("FCreateUserId <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("FCreateUserId >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FCreateUserId >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("FCreateUserId <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("FCreateUserId <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("FCreateUserId in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("FCreateUserId not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("FCreateUserId between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FCreateUserId not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNull() {
            addCriterion("FLastModifyTime is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNotNull() {
            addCriterion("FLastModifyTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeEqualTo(Date value) {
            addCriterion("FLastModifyTime =", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotEqualTo(Date value) {
            addCriterion("FLastModifyTime <>", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThan(Date value) {
            addCriterion("FLastModifyTime >", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FLastModifyTime >=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThan(Date value) {
            addCriterion("FLastModifyTime <", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("FLastModifyTime <=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIn(List<Date> values) {
            addCriterion("FLastModifyTime in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotIn(List<Date> values) {
            addCriterion("FLastModifyTime not in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
            addCriterion("FLastModifyTime between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("FLastModifyTime not between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdIsNull() {
            addCriterion("FLastModifyUserId is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdIsNotNull() {
            addCriterion("FLastModifyUserId is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdEqualTo(Integer value) {
            addCriterion("FLastModifyUserId =", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdNotEqualTo(Integer value) {
            addCriterion("FLastModifyUserId <>", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdGreaterThan(Integer value) {
            addCriterion("FLastModifyUserId >", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FLastModifyUserId >=", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdLessThan(Integer value) {
            addCriterion("FLastModifyUserId <", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("FLastModifyUserId <=", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdIn(List<Integer> values) {
            addCriterion("FLastModifyUserId in", values, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdNotIn(List<Integer> values) {
            addCriterion("FLastModifyUserId not in", values, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("FLastModifyUserId between", value1, value2, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FLastModifyUserId not between", value1, value2, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("FIsDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("FIsDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("FIsDelete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("FIsDelete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("FIsDelete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FIsDelete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("FIsDelete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("FIsDelete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("FIsDelete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("FIsDelete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsDelete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsDelete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andReportDescIsNull() {
            addCriterion("FReportDesc is null");
            return (Criteria) this;
        }

        public Criteria andReportDescIsNotNull() {
            addCriterion("FReportDesc is not null");
            return (Criteria) this;
        }

        public Criteria andReportDescEqualTo(String value) {
            addCriterion("FReportDesc =", value, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescNotEqualTo(String value) {
            addCriterion("FReportDesc <>", value, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescGreaterThan(String value) {
            addCriterion("FReportDesc >", value, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescGreaterThanOrEqualTo(String value) {
            addCriterion("FReportDesc >=", value, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescLessThan(String value) {
            addCriterion("FReportDesc <", value, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescLessThanOrEqualTo(String value) {
            addCriterion("FReportDesc <=", value, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescLike(String value) {
            addCriterion("FReportDesc like", value, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescNotLike(String value) {
            addCriterion("FReportDesc not like", value, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescIn(List<String> values) {
            addCriterion("FReportDesc in", values, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescNotIn(List<String> values) {
            addCriterion("FReportDesc not in", values, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescBetween(String value1, String value2) {
            addCriterion("FReportDesc between", value1, value2, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andReportDescNotBetween(String value1, String value2) {
            addCriterion("FReportDesc not between", value1, value2, "reportDesc");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardIsNull() {
            addCriterion("FCustomerBankCard is null");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardIsNotNull() {
            addCriterion("FCustomerBankCard is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardEqualTo(String value) {
            addCriterion("FCustomerBankCard =", value, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardNotEqualTo(String value) {
            addCriterion("FCustomerBankCard <>", value, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardGreaterThan(String value) {
            addCriterion("FCustomerBankCard >", value, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardGreaterThanOrEqualTo(String value) {
            addCriterion("FCustomerBankCard >=", value, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardLessThan(String value) {
            addCriterion("FCustomerBankCard <", value, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardLessThanOrEqualTo(String value) {
            addCriterion("FCustomerBankCard <=", value, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardLike(String value) {
            addCriterion("FCustomerBankCard like", value, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardNotLike(String value) {
            addCriterion("FCustomerBankCard not like", value, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardIn(List<String> values) {
            addCriterion("FCustomerBankCard in", values, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardNotIn(List<String> values) {
            addCriterion("FCustomerBankCard not in", values, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardBetween(String value1, String value2) {
            addCriterion("FCustomerBankCard between", value1, value2, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardNotBetween(String value1, String value2) {
            addCriterion("FCustomerBankCard not between", value1, value2, "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("FUuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("FUuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("FUuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("FUuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("FUuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("FUuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("FUuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("FUuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("FUuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("FUuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("FUuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("FUuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("FUuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("FUuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLikeInsensitive(String value) {
            addCriterion("upper(FCustomerName) like", value.toUpperCase(), "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerIdCardNumLikeInsensitive(String value) {
            addCriterion("upper(FCustomerIdCardNum) like", value.toUpperCase(), "customerIdCardNum");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLikeInsensitive(String value) {
            addCriterion("upper(FCustomerMobile) like", value.toUpperCase(), "customerMobile");
            return (Criteria) this;
        }

        public Criteria andReportNumLikeInsensitive(String value) {
            addCriterion("upper(FReportNum) like", value.toUpperCase(), "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportCodeLikeInsensitive(String value) {
            addCriterion("upper(FReportCode) like", value.toUpperCase(), "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportDescLikeInsensitive(String value) {
            addCriterion("upper(FReportDesc) like", value.toUpperCase(), "reportDesc");
            return (Criteria) this;
        }

        public Criteria andCustomerBankCardLikeInsensitive(String value) {
            addCriterion("upper(FCustomerBankCard) like", value.toUpperCase(), "customerBankCard");
            return (Criteria) this;
        }

        public Criteria andUuidLikeInsensitive(String value) {
            addCriterion("upper(FUuid) like", value.toUpperCase(), "uuid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_CreditReport
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_CreditReport
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}