package com.btjf.credit.report.decision.dock.model;

import java.io.Serializable;
import java.util.Date;

public class CreditReportDecisonDockLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FProductId
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FParmMap
     *
     * @mbg.generated
     */
    private String parmMap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FUrl
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FResultCode
     *
     * @mbg.generated
     */
    private String resultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FResultDesc
     *
     * @mbg.generated
     */
    private String resultDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FStartTime
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FEndTime
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FIsDelete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FCreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FReportDesc
     *
     * @mbg.generated
     */
    private String reportDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_CreditReportDecisonDockLog.FData
     *
     * @mbg.generated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FID
     *
     * @return the value of t_CreditReportDecisonDockLog.FID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FID
     *
     * @param id the value for t_CreditReportDecisonDockLog.FID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FProductId
     *
     * @return the value of t_CreditReportDecisonDockLog.FProductId
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FProductId
     *
     * @param productId the value for t_CreditReportDecisonDockLog.FProductId
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FParmMap
     *
     * @return the value of t_CreditReportDecisonDockLog.FParmMap
     *
     * @mbg.generated
     */
    public String getParmMap() {
        return parmMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FParmMap
     *
     * @param parmMap the value for t_CreditReportDecisonDockLog.FParmMap
     *
     * @mbg.generated
     */
    public void setParmMap(String parmMap) {
        this.parmMap = parmMap == null ? null : parmMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FUrl
     *
     * @return the value of t_CreditReportDecisonDockLog.FUrl
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FUrl
     *
     * @param url the value for t_CreditReportDecisonDockLog.FUrl
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FResultCode
     *
     * @return the value of t_CreditReportDecisonDockLog.FResultCode
     *
     * @mbg.generated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FResultCode
     *
     * @param resultCode the value for t_CreditReportDecisonDockLog.FResultCode
     *
     * @mbg.generated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FResultDesc
     *
     * @return the value of t_CreditReportDecisonDockLog.FResultDesc
     *
     * @mbg.generated
     */
    public String getResultDesc() {
        return resultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FResultDesc
     *
     * @param resultDesc the value for t_CreditReportDecisonDockLog.FResultDesc
     *
     * @mbg.generated
     */
    public void setResultDesc(String resultDesc) {
        this.resultDesc = resultDesc == null ? null : resultDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FStartTime
     *
     * @return the value of t_CreditReportDecisonDockLog.FStartTime
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FStartTime
     *
     * @param startTime the value for t_CreditReportDecisonDockLog.FStartTime
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FEndTime
     *
     * @return the value of t_CreditReportDecisonDockLog.FEndTime
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FEndTime
     *
     * @param endTime the value for t_CreditReportDecisonDockLog.FEndTime
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FIsDelete
     *
     * @return the value of t_CreditReportDecisonDockLog.FIsDelete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FIsDelete
     *
     * @param isDelete the value for t_CreditReportDecisonDockLog.FIsDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FCreateTime
     *
     * @return the value of t_CreditReportDecisonDockLog.FCreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FCreateTime
     *
     * @param createTime the value for t_CreditReportDecisonDockLog.FCreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FReportDesc
     *
     * @return the value of t_CreditReportDecisonDockLog.FReportDesc
     *
     * @mbg.generated
     */
    public String getReportDesc() {
        return reportDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FReportDesc
     *
     * @param reportDesc the value for t_CreditReportDecisonDockLog.FReportDesc
     *
     * @mbg.generated
     */
    public void setReportDesc(String reportDesc) {
        this.reportDesc = reportDesc == null ? null : reportDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_CreditReportDecisonDockLog.FData
     *
     * @return the value of t_CreditReportDecisonDockLog.FData
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_CreditReportDecisonDockLog.FData
     *
     * @param data the value for t_CreditReportDecisonDockLog.FData
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CreditReportDecisonDockLog other = (CreditReportDecisonDockLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getParmMap() == null ? other.getParmMap() == null : this.getParmMap().equals(other.getParmMap()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getResultCode() == null ? other.getResultCode() == null : this.getResultCode().equals(other.getResultCode()))
            && (this.getResultDesc() == null ? other.getResultDesc() == null : this.getResultDesc().equals(other.getResultDesc()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getReportDesc() == null ? other.getReportDesc() == null : this.getReportDesc().equals(other.getReportDesc()))
            && (this.getData() == null ? other.getData() == null : this.getData().equals(other.getData()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getParmMap() == null) ? 0 : getParmMap().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getResultCode() == null) ? 0 : getResultCode().hashCode());
        result = prime * result + ((getResultDesc() == null) ? 0 : getResultDesc().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getReportDesc() == null) ? 0 : getReportDesc().hashCode());
        result = prime * result + ((getData() == null) ? 0 : getData().hashCode());
        return result;
    }
}