package com.btjf.credit.report.decision.dock.mapper;

import com.btjf.credit.report.decision.dock.model.CreditReportDecisonDockLog;
import com.btjf.credit.report.decision.dock.model.CreditReportDecisonDockLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreditReportDecisonDockLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    long countByExample(CreditReportDecisonDockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int deleteByExample(CreditReportDecisonDockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int insert(CreditReportDecisonDockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int insertSelective(CreditReportDecisonDockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    List<CreditReportDecisonDockLog> selectByExampleWithBLOBs(CreditReportDecisonDockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    List<CreditReportDecisonDockLog> selectByExample(CreditReportDecisonDockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    CreditReportDecisonDockLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CreditReportDecisonDockLog record, @Param("example") CreditReportDecisonDockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CreditReportDecisonDockLog record, @Param("example") CreditReportDecisonDockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CreditReportDecisonDockLog record, @Param("example") CreditReportDecisonDockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CreditReportDecisonDockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CreditReportDecisonDockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_CreditReportDecisonDockLog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CreditReportDecisonDockLog record);
}